version: '3.8'

services:
  node1:
    image: distributedkeyvalue_v2:latest
    container_name: node1
    environment:
      - RAFT_NODE_ID=node1
      - RAFT_PEERS=node1:node1:9870,node2:node2:9870,node3:node3:9870
      - SERVER_PORT=8080
      - RAFT_BIND_ADDRESS=0.0.0.0  # Add this line

    ports:
      - "8081:8080"
      - "9871:9870"
    networks:
      - raft-network

  node2:
    image: distributedkeyvalue_v2:latest
    container_name: node2
    environment:
      - RAFT_NODE_ID=node2
      - RAFT_PEERS=node1:node1:9870,node2:node2:9870,node3:node3:9870
      - SERVER_PORT=8080
      - RAFT_BIND_ADDRESS=0.0.0.0
    ports:
      - "8082:8080"
      - "9872:9870"
    networks:
      - raft-network

  node3:
    image: distributedkeyvalue_v2:latest
    container_name: node3
    environment:
      - RAFT_NODE_ID=node3
      - RAFT_PEERS=node1:node1:9870,node2:node2:9870,node3:node3:9870
      - SERVER_PORT=8080
      - RAFT_BIND_ADDRESS=0.0.0.0
    ports:
      - "8083:8080"
      - "9873:9870"
    networks:
      - raft-network

networks:
  raft-network:
    driver: bridge