services:
  shard-manager:
    image: distributedkeyvalue_v3:latest  # Same image as nodes
    environment:
      - SPRING_PROFILES_ACTIVE=manager
    networks:
      - raft-network
    ports:
      - "8080:8080"
    depends_on:  # Ensure nodes start after the manager
      - shard1-node1
      - shard1-node2
      - shard1-node3
      - shard2-node1
      - shard2-node2
      - shard2-node3


  # Fix port conflict and typo
  load-balancer:  # Corrected service name
    image: distributedkeyvalue_v3:latest
    environment:
      - SPRING_PROFILES_ACTIVE=loadbalancer
    ports:
      - "8087:8080"  # Only expose load balancer
    networks:
      - raft-network  # Add to network
    depends_on:
      - shard-manager


  # Shard1 Nodes
  shard1-node1:
    image: distributedkeyvalue_v3:latest
    environment:
      - SPRING_PROFILES_ACTIVE=node  # Activate "node" profile
      - SHARD_ID=shard1
      - RAFT_NODE_ID=shard1-node1
      - RAFT_PEERS=shard1-node1:shard1-node1:9870,shard1-node2:shard1-node2:9870,shard1-node3:shard1-node3:9870
      - RAFT_BIND_ADDRESS=0.0.0.0
    ports:
      - "8081:8080"
      - "9871:9870"
    networks:
      - raft-network

  shard1-node2:
    image: distributedkeyvalue_v3:latest
    environment:
      - SPRING_PROFILES_ACTIVE=node  # Activate "node" profile
      - SHARD_ID=shard1
      - RAFT_NODE_ID=shard1-node2
      - RAFT_PEERS=shard1-node1:shard1-node1:9870,shard1-node2:shard1-node2:9870,shard1-node3:shard1-node3:9870
      - RAFT_BIND_ADDRESS=0.0.0.0
    ports:
      - "8082:8080"
      - "9872:9870"
    networks:
      - raft-network

  shard1-node3:
    image: distributedkeyvalue_v3:latest
    environment:
      - SPRING_PROFILES_ACTIVE=node  # Activate "node" profile
      - SHARD_ID=shard1
      - RAFT_NODE_ID=shard1-node3
      - RAFT_PEERS=shard1-node1:shard1-node1:9870,shard1-node2:shard1-node2:9870,shard1-node3:shard1-node3:9870
      - RAFT_BIND_ADDRESS=0.0.0.0
    ports:
      - "8083:8080"
      - "9873:9870"
    networks:
      - raft-network

  # Shard2 Nodes (similar to Shard1)
  shard2-node1:
    image: distributedkeyvalue_v3:latest
    environment:
      - SPRING_PROFILES_ACTIVE=node  # Activate "node" profile
      - SHARD_ID=shard2
      - RAFT_NODE_ID=shard2-node1
      - RAFT_PEERS=shard2-node1:shard2-node1:9870,shard2-node2:shard2-node2:9870,shard2-node3:shard2-node3:9870
      - RAFT_BIND_ADDRESS=0.0.0.0
    ports:
      - "8084:8080"
      - "9874:9870"
    networks:
      - raft-network

  shard2-node2:
    image: distributedkeyvalue_v3:latest
    environment:
      - SPRING_PROFILES_ACTIVE=node  # Activate "node" profile
      - SHARD_ID=shard2
      - RAFT_NODE_ID=shard2-node2
      - RAFT_PEERS=shard2-node1:shard2-node1:9870,shard2-node2:shard2-node2:9870,shard2-node3:shard2-node3:9870
      - RAFT_BIND_ADDRESS=0.0.0.0
    ports:
      - "8085:8080"
      - "9875:9870"
    networks:
      - raft-network

  shard2-node3:
    image: distributedkeyvalue_v3:latest
    environment:
      - SPRING_PROFILES_ACTIVE=node  # Activate "node" profile
      - SHARD_ID=shard2
      - RAFT_NODE_ID=shard2-node3
      - RAFT_PEERS=shard2-node1:shard2-node1:9870,shard2-node2:shard2-node2:9870,shard2-node3:shard2-node3:9870
      - RAFT_BIND_ADDRESS=0.0.0.0
    ports:
      - "8086:8080"
      - "9876:9870"
    networks:
      - raft-network

networks:
  raft-network:
    driver: bridge