spring:
  application:
    name: distributedKeyValue
  profiles:
    active: node  # Default profile (for nodes)


debug: true


raft:
  cluster:
    group-id: kv-store-group
    port: 9870
  client:
    retry:
          max-attempts: 5
          backoff-period: 2000


server:
  port: ${SERVER_PORT:8080}



shard:
  registration:
    enabled: true

http:
  pool:
    max-total: 200          # Total connections across all nodes
    default-max-per-route: 50 # Connections per node
    validate-after-inactivity: 5000 # ms
  timeouts:
    socket: 5000            # ms
    connect: 3000           # ms

---
spring:
  config:
    activate:
      on-profile: manager
  main:
    web-application-type: servlet  # Ensure the manager runs as a web server